### ISSUE TITLE
Possible duplication of effort

### ISSUE THREAD

**Issue by gep13** [AnthonyArzola/Cake.AppCenter#1]
@AnthonyArzola I wanted to reach out to let you know about this repository:

https://github.com/cake-contrib/Cake.AppCenter

Which I suspect might be a duplicate of some of the work that you are doing here.

@MihaMarkic has just pushed a Cake.AppCenter package to NuGet.org, so you might see errors when/if you try to push your package there (not sure if this is something you are planning or not).

I wasn't aware of this repository when I created the Cake.AppCenter repository in the cake-contrib Organisation, if I had, I would have reached out sooner.

Rather than duplicating effort, would it make sense to combine efforts?

**Comment by AnthonyArzola** [comment]
Hi @gep13 Looks like that repo is way farther along. I'll probably just deprecate or delete my repo. 😢

**Comment by gep13** [comment]
If you are interested, I could add you to the new Cake.AppCenter repo so that you can help out. I am sure that Miha would welcome the help.

**Comment by MihaMarkic** [comment]
Sure, why not. 
Mind though that almost all of it is autogenerated (actually it took me a couple of hours to adjust generator from Cake.MobileCenter) :)

**Comment by gep13** [comment]
@AnthonyArzola would you like me to add you to the cake-contrib organisation, with permissions for this repository?

**Comment by AnthonyArzola** [comment]
@gep13 Yes, please!

**Comment by gep13** [comment]
@AnthonyArzola I have invited you to the Cake-Contrib Organisation, you should have an email asking you to join.

If you have twitter and email, if you can let me know both, I will follow you from the cake-contrib twitter account, and also get you added to the Cake-Contrib Slack Channel.

Thanks again!

**Comment by AnthonyArzola** [comment]
@gep13 I accepted Cake-Contrib invitation. My e-mail is my username above @gmail.com

**Comment by AnthonyArzola** [comment]
Update REAME file to indicate this repo will be deprecated in favor of Cake.AppCenter written and maintained by cake-contrib.

**Comment by gep13** [comment]
@AnthonyArzola I have just sent you an invite to join the Cake-Contrib Slack Team.

**Comment by AnthonyArzola** [comment]
Awesome! I'm in - Thank you!
